/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
import { Route as ImpactoRouteImport } from './routes/impacto'
import { Route as CreditoRouteImport } from './routes/credito'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as IndexRouteImport } from './routes/index'

const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactoRoute = ImpactoRouteImport.update({
  id: '/impacto',
  path: '/impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditoRoute = CreditoRouteImport.update({
  id: '/credito',
  path: '/credito',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contactos': typeof ContactosRoute
  '/credito': typeof CreditoRoute
  '/impacto': typeof ImpactoRoute
  '/simulacao': typeof SimulacaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contactos': typeof ContactosRoute
  '/credito': typeof CreditoRoute
  '/impacto': typeof ImpactoRoute
  '/simulacao': typeof SimulacaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/contactos': typeof ContactosRoute
  '/credito': typeof CreditoRoute
  '/impacto': typeof ImpactoRoute
  '/simulacao': typeof SimulacaoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-nos': typeof SobreNosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/como-funciona'
    | '/contactos'
    | '/credito'
    | '/impacto'
    | '/simulacao'
    | '/sitemap.xml'
    | '/sobre-nos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/como-funciona'
    | '/contactos'
    | '/credito'
    | '/impacto'
    | '/simulacao'
    | '/sitemap.xml'
    | '/sobre-nos'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/contactos'
    | '/credito'
    | '/impacto'
    | '/simulacao'
    | '/sitemap.xml'
    | '/sobre-nos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  ContactosRoute: typeof ContactosRoute
  CreditoRoute: typeof CreditoRoute
  ImpactoRoute: typeof ImpactoRoute
  SimulacaoRoute: typeof SimulacaoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreNosRoute: typeof SobreNosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacto': {
      id: '/impacto'
      path: '/impacto'
      fullPath: '/impacto'
      preLoaderRoute: typeof ImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credito': {
      id: '/credito'
      path: '/credito'
      fullPath: '/credito'
      preLoaderRoute: typeof CreditoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  ContactosRoute: ContactosRoute,
  CreditoRoute: CreditoRoute,
  ImpactoRoute: ImpactoRoute,
  SimulacaoRoute: SimulacaoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreNosRoute: SobreNosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
